# Generated by Django 5.2.6 on 2025-09-24 00:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Produto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('descrição', models.CharField(max_length=50)),
                ('preço', models.DecimalField(decimal_places=2, max_digits=12)),
                ('imagem', models.ImageField(upload_to='produtos/')),
            ],
            options={
                'ordering': ['nome'],
            },
        ),
        migrations.DeleteModel(
            name='Carro',
        ),
    ]
