# Generated by Django 5.2.6 on 2025-09-24 01:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_produto_delete_carro'),
    ]

    operations = [
        migrations.AddField(
            model_name='produto',
            name='categoria',
            field=models.CharField(choices=[('tecnologia', 'Tecnologia'), ('vestuario', 'Vestuário')], default='Tecnologia', max_length=20),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='produto',
            name='descrição',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='produto',
            name='imagem',
            field=models.ImageField(blank=True, null=True, upload_to='produtos/'),
        ),
        migrations.AlterField(
            model_name='produto',
            name='preço',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
    ]
